#!/usr/bin/env ruby

$:.unshift File.expand_path(File.join(File.dirname(__FILE__), *%w[.. lib]))

require "anki/wotd"
require "anki/connect"
require "oxford_dictionary"
require 'yaml'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: anki-word [options]"
  opts.on('-w', '--words "word1 word2"', 'Words List (space seperated)') { |v| options[:words] = v.gsub('=', '').strip.split(' ').compact }
  opts.on('-p', '--print', 'Print Output Only') { |v| options[:print] = true }
end.parse!

ANKI_CONFIG = YAML.load_file(File.expand_path('~/.anki-wotd.yml'))

Anki::Connect.configure do |config|
  config.deck_name = 'Default'
  config.model_name = 'Cloze'
  config.oxford_dictionary_client = OxfordDictionary.new(app_id: ANKI_CONFIG['OXFORD_DICTIONARY_APP_ID'], app_key: ANKI_CONFIG['OXFORD_DICTIONARY_APP_KEY'])
end

definitions = Anki::Wotd::Words.new(words: options[:words])
cards = Anki::Wotd::Cards.new(definitions: definitions)

if options[:print]
  cards.each(&:print)
else
  Anki::Wotd::Ankify.new(cards: cards).create
end
